### ISSUE TITLE
Unclear documentation: how to install plugin from debian package

### ISSUE THREAD

**Issue by TomFernandes** [jceb/vim-orgmode#170]
Hi,

I'd like to install the plugin from the debian-package but don't understand how. The documentation says:
"For installing the plugin form the resulting vim-orgmode_X.X.X-X.deb file, please refer to the Installation section."
But the Installation section only mentions the file "orgmode.vba", which is not present in the Debian package. What am I missing? I haven't used vim-plugins before, so this may be a general question. From what I read about general vim-plugin documentation I was not able to get it work.

Warm regards,

Tom

**Comment by Shurakai** [comment]
@TomFernandes I would recommend you look at Vundle / Pathogen. These are two plugins for vim that very conveniently install and manage software; no .deb file needs to be build, you can just use the git repositories. Everything is stored in ~/.vim/bundle/plugin-name, where plugin-name is obviously the name of the plugin you want to install.

The reason you should look at this is that you can manage all plugins by this approach, otherwise you would have to build your .deb files for most of the plugins by yourself.  :)

**Comment by jceb** [comment]
I guess there's not much to add here.
