### ISSUE TITLE
Setting a colorscheme removes all syntax highlighting by orgmode

### ISSUE THREAD

**Issue by brahm92** [jceb/vim-orgmode#238]
Hi, my vimrc loads vim-orgmode as part of Vundle calls. Later, I choose a colorscheme "summerfruit256" for all my .org files via autocommands. After doing this, all syntax highlighting by orgmode dissapears.

I am setting syntax highlighting after choosing a colorscheme with "syntax on".

This issue occurs at varying levels with other schemes. Gruvbox for instance, shows *title* as bold. But any other colorscheme, like industry or peachpuff or elflord do not show *title* as bold. What could be the issue?

Just let me know if any other information is needed.

**Comment by Ron89** [comment]
The difference between `Gruvbox` and `elflord` is probably because the two
scheme define highlight for keywords differently. In our code, we circulate
`Title`, `Constant`, `Identifier`, `Statement`, `PreProc`, `Type`, `Special`
for different layers of headings, as specified in
`g:org_heading_highlight_colors`.

```
	let g:org_heading_highlight_colors = ['Title', 'Constant', 'Identifier', 'Statement', 'PreProc', 'Type', 'Special']
```

In colorscheme `Gruvbox`, `Title` is set as bold, while in `elflord`,
`Identifier` is set as bold. Hence the differences. In `Summerfruit256`,
`Title` is defined as normal font with black color, And maybe that's why you
find the syntax not working?

If you feel it's not the case, could you give me the output of
```
echo &filetype
```
and more detailed symptom to me?

**Comment by brahm92** [comment]
This could indeed be the case. I will check this out. In the meanwhile, could you kindly suggest a good color scheme to use with orgmode? For example, the colorscheme in the demo image on the github page? Or any other that you have personally used?


Thank you for your help!





On Tue, May 17, 2016 at 5:33 AM -0700, "HE Chong" <notifications@github.com> wrote:





The difference between `Gruvbox` and `elflord` is probably because the two
scheme define highlight for keywords differently. In our code, we circulate
`Title`, `Constant`, `Identifier`, `Statement`, `PreProc`, `Type`, `Special`
for different layers of headings, as specified in
`g:org_heading_highlight_colors`.

```
        let g:org_heading_highlight_colors = ['Title', 'Constant', 'Identifier', 'Statement', 'PreProc', 'Type', 'Special']
```

In colorscheme `Gruvbox`, `Title` is set as bold, while in `elflord`,
`Identifier` is set as bold. Hence the differences. In `Summerfruit256`,
`Title` is defined as normal font with black color, And maybe that's why you
find the syntax not working?

If you feel it's not the case, could you give me the output of
```
echo &filetype
```
and more detailed symptom to me?


---

**Comment by Ron89** [comment]
I don't know Jan's color settings. Personally I'm using dark `gruvbox` with one
personal setting

```
highlight Folded cterm=bold gui=bold 
```

so that the folded content can be more visible.

**Comment by Ron89** [comment]
I think the issue is solved at this point. Case closed. :)
