### ISSUE TITLE
E117: Unknown function: <SNR>254_ReadTodoKeywords

### ISSUE THREAD

**Issue by Bingbingyan** [jceb/vim-orgmode#312]
E117: Unknown function: <SNR>254_ReadTodoKeywords

macos 10.14.2
NVIM v0.3.1
python 3.7

![image](https://user-images.githubusercontent.com/8036794/51100284-46548b80-1810-11e9-9ee3-d981d1906c1e.png)

**Comment by Coffei** [comment]
Seeing the same thing whenever I open orgmode doc in vim with this plugin.

**Comment by Oddegamra** [comment]
For me, this issue was caused by the [vim-polyglot](https://github.com/sheerun/vim-polyglot) addon, which contains its own (at the moment broken - see sheerun/vim-polyglot#360) version of orgmode. Since that plugin also defines the `g:loaded_org_syntax` global, the function definition for ReadTodoKeywords is never executed.

**Comment by Coffei** [comment]
Took me a while to get back to this issue, but I confirm the above, it was vim-polyglot interfering. Adding `org` to `g:polyglot_disabled` solved the issue.

**Comment by XVilka** [comment]
Since it was removed in vim-polyglot, can you please confirm that issue gone: https://github.com/sheerun/vim-polyglot/commit/288b0d2423e0338c6ed595bca33b7fe08f2ea5a8

**Comment by Coffei** [comment]
Yep, it seems to be gone. Updated polyglot, removed `org` from `g:polyglot_disabled` and all works fine. Thanks all!

**Comment by Maltimore** [comment]
Shouldn't this issue be closed then?
